# Generated by Django 4.1.5 on 2023-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.JSONField(blank=True, null=True, verbose_name=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('problem', models.TextField()),
                ('description_status_cancel', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('accept_time', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('brandpart', models.JSONField(null=True, verbose_name=dict)),
                ('type_phone', models.CharField(choices=[('internal', 'Internal'), ('city', 'City')], max_length=8)),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('accept', 'Accept'), ('wating', 'Wating'), ('cancel', 'Cancel')], default='wating', max_length=8)),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
    ]
