# Generated by Django 4.1.5 on 2023-02-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone_line', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.branch'),
        ),
        migrations.AddField(
            model_name='brandpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_line.part'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'finished'), _negated=True), models.Q(('status', 'cancel'), _negated=True)), fields=('phone_number',), name='uniqe with status'),
        ),
    ]
