# Generated by Django 4.1.5 on 2023-01-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone_line', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.place'),
        ),
    ]
