# Generated by Django 4.1.5 on 2023-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_line', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.JSONField(blank=True, null=True, verbose_name=dict),
        ),
    ]
