# Generated by Django 4.1.5 on 2023-02-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BrandPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.JSONField(blank=True, null=True, verbose_name=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=12, unique=True)),
                ('have_part', models.BooleanField()),
                ('user', models.CharField(max_length=30)),
                ('have_seal_number', models.BooleanField()),
                ('seal_number', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('broken_down', 'Broken_down'), ('in_repair', 'In_repair'), ('in_work', 'In_work')], default='in_work', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('problem', models.TextField()),
                ('description_status_cancel', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('accept_time', models.DateTimeField(null=True)),
                ('brandpart', models.JSONField(null=True, verbose_name=dict)),
                ('delivery_user', models.CharField(max_length=20, null=True)),
                ('transfere_user', models.CharField(max_length=20, null=True)),
                ('delivery_operator', models.CharField(blank=True, max_length=20, null=True)),
                ('transfere_oprator', models.CharField(blank=True, max_length=20, null=True)),
                ('unrepairable_time', models.DateTimeField(blank=True, null=True)),
                ('repair_in_city_time', models.DateTimeField(blank=True, null=True)),
                ('provide_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('repair_in_city', 'Repair_In_City'), ('unrepairable', 'Unrepairable'), ('finished', 'Finished'), ('provide', 'Provide'), ('wating', 'Wating'), ('cancel', 'Cancel')], default='wating', max_length=14)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.device')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('visible_in_device', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.category')),
            ],
        ),
    ]
