# Generated by Django 4.1.5 on 2023-01-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('identification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=12)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('brandcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.brandcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('problem', models.TextField()),
                ('description_status_cancel', models.TextField()),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('accept_time', models.DateTimeField()),
                ('finished_time', models.DateTimeField()),
                ('cancel_time', models.DateTimeField()),
                ('delivery_user', models.CharField(max_length=20)),
                ('transfere_user', models.CharField(max_length=20)),
                ('delivery_operator', models.CharField(max_length=20)),
                ('transfere_oprator', models.CharField(max_length=20)),
                ('unrepairable_time', models.DateTimeField()),
                ('repair_in_city_time', models.DateTimeField()),
                ('provide_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('repair_in_city', 'Repair_In_City'), ('unrepairable', 'Unrepairable'), ('finished', 'Finished'), ('provide', 'Provide'), ('wating', 'Wating'), ('accept', 'Accept'), ('cancel', 'Cancel')], max_length=14)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('number', models.JSONField(verbose_name=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.part'),
        ),
    ]
