# Generated by Django 4.1.5 on 2023-02-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.branch'),
        ),
        migrations.AddField(
            model_name='device',
            name='brandcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.brandcategory'),
        ),
        migrations.AddField(
            model_name='device',
            name='brandpart',
            field=models.ManyToManyField(null=True, to='device.brandpart'),
        ),
        migrations.AddField(
            model_name='brandpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.part'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.category'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'finished'), _negated=True), models.Q(('status', 'cancel'), _negated=True)), fields=('device',), name='unique with status'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'category')},
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('have_seal_number', True), ('seal_number__isnull', False)), models.Q(('have_seal_number', False), ('seal_number__isnull', True)), _connector='OR'), name='check have_seal_number'),
        ),
        migrations.AlterUniqueTogether(
            name='brandpart',
            unique_together={('name', 'part')},
        ),
        migrations.AlterUniqueTogether(
            name='brandcategory',
            unique_together={('name', 'category')},
        ),
    ]
