# Generated by Django 4.1.5 on 2023-01-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandcategory',
            unique_together={('name', 'category')},
        ),
    ]
