# Generated by Django 4.1.5 on 2023-01-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_alter_part_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'brand')},
        ),
    ]
