# Generated by Django 4.1.5 on 2023-01-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_part_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'brand', 'category')},
        ),
    ]
