# Generated by Django 4.1.5 on 2023-01-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'place')},
        ),
    ]
